const projects = [
  {
    url: "https://youtubebyshamailabbas.netlify.app/",
    title: "Youtube clone with complete backend",
    desc: "A fully functional Youtube Clone Webapp having following features",
    features: [
      "User Authantication",
      "Video Uploads",
      "Subscriptions",
      "Comments",
      "Like/Dislike",
      "View Counts",
    ],
    techused: ["MongoDB", "Reactjs", "React redux", "Nodejs", "AWS S3"],
  },
  {
    url: "https://areagg.netlify.app/",
    title: "Areagg-A Social Media Platform",
    desc: "A fully functional Social Media Platform having following features",
    features: [
      "User Authantication",
      "Upload Posts",
      "Follow Users",
      "Comments",
      "Likes",
      "Chat",
    ],
    techused: [
      "MongoDB",
      "Reactjs",
      "React redux",
      "Nodejs",
      "redis",
      "AWS S3",
    ],
  },
  {
    url: "https://amazonclonebyshamail.netlify.app/",
    title: "Amazon Clone Web App using React Redux",
    desc: "A fully functional E-commerce Webapp having following features",
    features: [
      "User Authantication",
      "UserDashboard",
      "AdminDashboard",
      "Payment Integration",
      "Database Integration",
    ],
    techused: ["Firebase", "Reactjs", "React redux", "Nodejs", "AWS Lambda"],
  },
  {
    url: "https://beachresortbooking.netlify.app/",
    title: "Hotel Booking Web App using React Redux",
    desc: "A fully functional Hotel Booking Webapp having following features",
    features: [
      "User Authantication",
      "UserDashboard",
      "AdminDashboard",
      "Sorting",
      "Database Integration",
    ],
    techused: ["Firebase", "Reactjs", "React redux", "Nodejs"],
  },

  {
    url: "https://fiverr-clone.vercel.app/",
    title: "Fiverr Clone with Backend",
    desc: "Fiverr Clone with Backend having following features",
    features: [
      "User Authantication",
      "Place Order",
      "Create Gigs",
      "Payment Integration",
      "Message Client",
    ],
    techused: [
      "MySQL",
      "Reactjs",
      "React redux",
      "Nodejs",
      "Graphql",
      "AWS S3",
    ],
  },

  {
    url: "https://gmailclonebyshamail.netlify.app/",
    title: "Gmail Clone using Firebase and React Redux",
    desc: "A fully functional Gmail Clone with following features",
    features: [
      "User Authantication",
      "Send Emails",
      "Receive Emails",
      "Persistant Login",
      "Database Integration",
    ],
    techused: ["Firebase", "Reactjs", "React redux", "Nodejs"],
  },
  {
    url: "https://airbnbclonebyshamail.netlify.app/",
    title: ".....AirBnb Clone.....",
    desc: "A Frontend Clone with following features",
    features: ["DatePicker", "Search bar", "Explore Nearby"],
    techused: ["Material UI", "Reactjs", "React redux"],
  },
  {
    url: "https://gainimpactchatapp.netlify.app/",
    title: "One to One Chat App called Gain Impact Chat",
    desc: "A fully functional Chat App having following features",
    features: [
      "User Authantication",
      "Real Time Chat",
      "User's Last Activity",
      "Timestamp",
    ],
    techused: ["MongoDB", "Reactjs", "Context Api", "Nodejs", "GraphQL"],
  },
];
module.exports = projects;
